import { createClient } from '@supabase/supabase-js';
import { env, isConfigured } from '@/config/env';

// Create Supabase client
export const supabase = createClient(
  env.supabase.url || 'https://placeholder.supabase.co',
  env.supabase.anonKey || 'placeholder-key',
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

// Helper to check if Supabase is properly configured
export function checkSupabaseConfig() {
  if (!isConfigured.supabase) {
    console.warn(
      '⚠️ Supabase is not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env file'
    );
    return false;
  }
  return true;
}

// Export types for Database tables (will be auto-generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      optimized_routes: {
        Row: {
          id: string;
          created_by: string | null;
          route_name: string | null;
          optimization_date: string;
          vehicles: any[];
          deliveries: any[];
          routes: any[];
          total_distance: number;
          total_cost: number;
          fuel_consumption: number;
          co2_reduction: number;
          efficiency_gain: number;
          unassigned_deliveries: any[];
          status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
          created_at: string;
          updated_at: string;
          completed_at: string | null;
          notes: string | null;
        };
        Insert: Partial<Database['public']['Tables']['optimized_routes']['Row']>;
        Update: Partial<Database['public']['Tables']['optimized_routes']['Row']>;
      };
      fatigue_monitoring_sessions: {
        Row: {
          id: string;
          driver_id: string;
          vehicle_id: string | null;
          start_time: string;
          end_time: string | null;
          duration_minutes: number | null;
          total_alerts: number;
          critical_alerts: number;
          warning_alerts: number;
          max_fatigue_score: number;
          avg_fatigue_score: number;
          breaks_taken: number;
          total_break_time_minutes: number;
          session_status: 'active' | 'completed' | 'interrupted';
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['fatigue_monitoring_sessions']['Row']>;
        Update: Partial<Database['public']['Tables']['fatigue_monitoring_sessions']['Row']>;
      };
      fatigue_alerts: {
        Row: {
          id: string;
          session_id: string;
          driver_id: string;
          alert_type: 'eyes_closed' | 'yawning' | 'head_nodding' | 'micro_sleep' | 'prolonged_driving';
          severity: 'low' | 'medium' | 'high';
          fatigue_score: number;
          fatigue_level: 'green' | 'yellow' | 'red';
          metrics: any;
          description: string;
          action_taken: string | null;
          acknowledged: boolean;
          acknowledged_at: string | null;
          acknowledged_by: string | null;
          timestamp: string;
          latitude: number | null;
          longitude: number | null;
        };
        Insert: Partial<Database['public']['Tables']['fatigue_alerts']['Row']>;
        Update: Partial<Database['public']['Tables']['fatigue_alerts']['Row']>;
      };
      chatbot_conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          messages: any[];
          message_count: number;
          avg_confidence: number | null;
          total_sources_referenced: number;
          status: 'active' | 'archived' | 'deleted';
          created_at: string;
          updated_at: string;
          last_message_at: string;
        };
        Insert: Partial<Database['public']['Tables']['chatbot_conversations']['Row']>;
        Update: Partial<Database['public']['Tables']['chatbot_conversations']['Row']>;
      };
      chatbot_knowledge_base: {
        Row: {
          id: string;
          title: string;
          category: 'vehicle_manual' | 'rndc_regulation' | 'company_policy' | 'incident_history' | 'other';
          content: string;
          summary: string | null;
          document_metadata: any;
          tags: string[];
          embedding: number[] | null;
          url: string | null;
          file_path: string | null;
          published: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Partial<Database['public']['Tables']['chatbot_knowledge_base']['Row']>;
        Update: Partial<Database['public']['Tables']['chatbot_knowledge_base']['Row']>;
      };
      chatbot_messages: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: 'user' | 'assistant' | 'system';
          content: string;
          confidence: number | null;
          sources_referenced: any[];
          suggested_actions: any[];
          user_feedback: 'helpful' | 'not_helpful' | 'partially_helpful' | null;
          user_rating: number | null;
          timestamp: string;
        };
        Insert: Partial<Database['public']['Tables']['chatbot_messages']['Row']>;
        Update: Partial<Database['public']['Tables']['chatbot_messages']['Row']>;
      };
    };
    Views: {};
    Functions: {
      get_driver_fatigue_stats: {
        Args: { driver_uuid: string; days_back?: number };
        Returns: {
          total_sessions: number;
          total_alerts: number;
          critical_alerts: number;
          avg_fatigue_score: number;
          total_driving_hours: number;
        }[];
      };
      get_top_efficient_routes: {
        Args: { limit_count?: number };
        Returns: {
          id: string;
          route_name: string | null;
          efficiency_gain: number;
          total_distance: number;
          co2_reduction: number;
          optimization_date: string;
        }[];
      };
      get_active_conversations: {
        Args: { limit_count?: number };
        Returns: {
          id: string;
          title: string | null;
          message_count: number;
          last_message_at: string;
          user_id: string;
        }[];
      };
    };
  };
};
